# Generated by Django 4.2.30 on 2026-07-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('mouse_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('genotype', models.CharField(blank=True, max_length=100)),
                ('crossing', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('protocol_start_date', models.DateField(blank=True, null=True)),
                ('cull_date', models.DateField(blank=True, null=True)),
                ('custom_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Mouse',
                'verbose_name_plural': 'Mice',
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('procedure_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Procedure type',
                'verbose_name_plural': 'Procedure types',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('protocol_id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol_number', models.IntegerField()),
                ('licence_reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='lab.mouse')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='lab.proceduretype')),
            ],
        ),
        migrations.AddField(
            model_name='mouse',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mice', to='lab.protocol'),
        ),
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('mouse', 'procedure_type'), name='uq_mouse_procedure'),
        ),
    ]
