# Generated by Django 4.2.30 on 2026-07-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_project_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingRecording',
            fields=[
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_date', models.DateField()),
                ('recording_path', models.TextField()),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('objective', models.CharField(blank=True, max_length=100)),
                ('pixel_size_x', models.FloatField(blank=True, null=True)),
                ('pixel_size_y', models.FloatField(blank=True, null=True)),
                ('pixel_size_z', models.FloatField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('frames', models.PositiveIntegerField(blank=True, null=True)),
                ('first_frame', models.PositiveIntegerField(blank=True, null=True)),
                ('last_frame', models.PositiveIntegerField(blank=True, null=True)),
                ('n_channels', models.PositiveSmallIntegerField(default=1)),
                ('discarded', models.BooleanField(default=False)),
                ('anaesthetic', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_recordings', to='lab.experiment')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_recordings', to='lab.mouse')),
            ],
            options={
                'ordering': ['-recording_date', 'mouse', 'sequence_number'],
            },
        ),
    ]
