# Generated by Django 4.2.30 on 2026-07-25 10:25

from django.db import migrations

def create_default_protocols(apps, schema_editor):
    Protocol = apps.get_model("lab", "Protocol")

    default_protocols = [
        {
            "protocol_number": 1,
            "licence_reference": "PP123456",
            "description": "My protocol description",
            "name": "Protocol 1",
        },


    ]

    for protocol_data in default_protocols:
        Protocol.objects.get_or_create(**protocol_data)


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_imagingrecording'),
    ]

    operations = [
        migrations.RunPython(create_default_protocols),
    ]
