# Generated by Django 4.2.30 on 2026-07-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20260725_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABRRecording',
            fields=[
                ('abr_recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_date', models.DateField()),
                ('recording_path', models.TextField()),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('anaesthetic', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abr_recordings', to='lab.experiment')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abr_recordings', to='lab.mouse')),
            ],
            options={
                'ordering': ['-recording_date', 'mouse', 'sequence_number'],
            },
        ),
    ]
