# Generated by Django 4.2.30 on 2026-07-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_abrrecording'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abrrecording',
            old_name='recording_path',
            new_name='raw_data_path',
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='click_threshold_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_12khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_18khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_24khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_30khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_36khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_3khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_42khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abrrecording',
            name='threshold_6khz_db',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
