# Generated by Django 4.2.30 on 2026-07-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_rename_recording_path_abrrecording_raw_data_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagingrecording',
            old_name='pixel_size_x',
            new_name='pixel_height',
        ),
        migrations.RenameField(
            model_name='imagingrecording',
            old_name='pixel_size_z',
            new_name='pixel_size_um',
        ),
        migrations.RenameField(
            model_name='imagingrecording',
            old_name='pixel_size_y',
            new_name='pixel_width',
        ),
        migrations.RemoveField(
            model_name='imagingrecording',
            name='first_frame',
        ),
        migrations.RemoveField(
            model_name='imagingrecording',
            name='last_frame',
        ),
    ]
