# Generated by Django 4.2.30 on 2026-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_rename_pixel_size_x_imagingrecording_pixel_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='crossing_type',
            field=models.CharField(blank=True, choices=[('WT', 'Wild Type'), ('Single', 'Single Mutation'), ('Double_triple', 'Crossing')], max_length=20),
        ),
        migrations.AddField(
            model_name='procedure',
            name='lab_book_page',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='procedure',
            name='lab_member',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
