# Generated by Django 4.2.30 on 2026-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_mouse_crossing_type_procedure_lab_book_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='mouse_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
