# Generated by Django 4.2.30 on 2026-07-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_mouse_mouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='lab.protocol'),
        ),
    ]
