# Generated by Django 4.2.30 on 2026-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_procedure_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='tattoo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
