# Generated by Django 4.2.30 on 2026-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_mouse_tattoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='severity',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=10),
        ),
    ]
