# Generated by Django 4.2.30 on 2026-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_mouse_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
