# Generated by Django 4.2.30 on 2026-07-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_remove_procedure_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
