# Generated by Codex on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0018_procedure_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abrrecording",
            old_name="abr_recording_id",
            new_name="recording_id",
        ),
        migrations.RenameField(
            model_name="abrrecording",
            old_name="raw_data_path",
            new_name="data_path",
        ),
        migrations.RenameField(
            model_name="imagingrecording",
            old_name="recording_path",
            new_name="data_path",
        ),
        migrations.AlterField(
            model_name="abrrecording",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="abrrecording",
            name="mouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.mouse",
            ),
        ),
        migrations.AlterField(
            model_name="imagingrecording",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="imagingrecording",
            name="mouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.mouse",
            ),
        ),
    ]
