# Generated by Codex on 2026-07-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0019_recording_superclass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedure",
            name="protocol",
        ),
    ]
