# Generated by Codex on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0020_remove_procedure_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abrrecording",
            name="mouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.mouse",
            ),
        ),
        migrations.AlterField(
            model_name="imagingrecording",
            name="mouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab.mouse",
            ),
        ),
    ]
