# Generated by Django 4.2.30 on 2026-07-29 08:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_alter_recording_mouse_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='max_severity',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=10),
        ),

    ]
