# Generated by Django 4.2.30 on 2026-07-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_protocol_max_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lab_member',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
