# Generated by Codex on 2026-07-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0024_experiment_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingType",
            fields=[
                (
                    "recording_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("plural_name", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecordingField",
            fields=[
                (
                    "recording_field_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("key", models.SlugField()),
                ("label", models.CharField(max_length=200)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("units", models.CharField(blank=True, max_length=50)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("display_in_table", models.BooleanField(default=True)),
                ("filterable", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "recording_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="lab.recordingtype",
                    ),
                ),
            ],
            options={
                "ordering": ["recording_type", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "recording_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("recording_date", models.DateField()),
                ("sequence_number", models.PositiveIntegerField(default=1)),
                ("data_path", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("values", models.JSONField(blank=True, default=dict)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recordings",
                        to="lab.experiment",
                    ),
                ),
                (
                    "mouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to="lab.mouse",
                    ),
                ),
                (
                    "recording_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recordings",
                        to="lab.recordingtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-recording_date", "mouse", "sequence_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="recordingfield",
            constraint=models.UniqueConstraint(
                fields=("recording_type", "key"),
                name="unique_recording_field_key_per_type",
            ),
        ),
    ]
