# Generated by Codex on 2026-07-30

from django.db import migrations


IMAGING_FIELDS = [
    ("objective", "Objective", "text", None, True, 10),
    ("pixel_width", "Pixel width", "float", None, False, 20),
    ("pixel_height", "Pixel height", "float", None, False, 30),
    ("pixel_size_um", "Pixel size", "float", None, False, 40),
    ("fps", "FPS", "float", None, True, 50),
    ("frames", "Frames", "integer", None, True, 60),
    ("n_channels", "Channels", "integer", 1, False, 70),
    ("discarded", "Discarded", "boolean", False, True, 80),
    ("anaesthetic", "Anaesthetic", "text", None, False, 90),
]


ABR_FIELDS = [
    ("anaesthetic", "Anaesthetic", "text", None, False, 10),
    ("click_threshold_db", "Click threshold", "integer", None, True, 20),
    ("threshold_3khz_db", "3 kHz", "integer", None, True, 30),
    ("threshold_6khz_db", "6 kHz", "integer", None, True, 40),
    ("threshold_12khz_db", "12 kHz", "integer", None, True, 50),
    ("threshold_18khz_db", "18 kHz", "integer", None, True, 60),
    ("threshold_24khz_db", "24 kHz", "integer", None, True, 70),
    ("threshold_30khz_db", "30 kHz", "integer", None, True, 80),
    ("threshold_36khz_db", "36 kHz", "integer", None, True, 90),
    ("threshold_42khz_db", "42 kHz", "integer", None, True, 100),
]


def create_recording_type(apps, name, plural_name, slug, field_specs):
    RecordingType = apps.get_model("lab", "RecordingType")
    RecordingField = apps.get_model("lab", "RecordingField")

    recording_type, _ = RecordingType.objects.update_or_create(
        slug=slug,
        defaults={
            "name": name,
            "plural_name": plural_name,
            "active": True,
        },
    )

    for key, label, data_type, default_value, display_in_table, order in field_specs:
        RecordingField.objects.update_or_create(
            recording_type=recording_type,
            key=key,
            defaults={
                "label": label,
                "data_type": data_type,
                "required": False,
                "choices": [],
                "units": "",
                "default_value": default_value,
                "active": True,
                "display_in_table": display_in_table,
                "filterable": False,
                "order": order,
            },
        )

    return recording_type


def migrate_recordings(apps, schema_editor):
    Recording = apps.get_model("lab", "Recording")
    ImagingRecording = apps.get_model("lab", "ImagingRecording")
    ABRRecording = apps.get_model("lab", "ABRRecording")

    imaging_type = create_recording_type(
        apps,
        "Imaging Recording",
        "Imaging recordings",
        "imaging",
        IMAGING_FIELDS,
    )
    abr_type = create_recording_type(
        apps,
        "ABR Recording",
        "ABR recordings",
        "abr",
        ABR_FIELDS,
    )

    for recording in ImagingRecording.objects.all().iterator():
        Recording.objects.create(
            mouse_id=recording.mouse_id,
            experiment_id=recording.experiment_id,
            recording_type=imaging_type,
            recording_date=recording.recording_date,
            sequence_number=recording.sequence_number,
            data_path=recording.data_path,
            notes=recording.notes,
            values={
                "objective": recording.objective,
                "pixel_width": recording.pixel_width,
                "pixel_height": recording.pixel_height,
                "pixel_size_um": recording.pixel_size_um,
                "fps": recording.fps,
                "frames": recording.frames,
                "n_channels": recording.n_channels,
                "discarded": recording.discarded,
                "anaesthetic": recording.anaesthetic,
            },
        )

    for recording in ABRRecording.objects.all().iterator():
        Recording.objects.create(
            mouse_id=recording.mouse_id,
            experiment_id=recording.experiment_id,
            recording_type=abr_type,
            recording_date=recording.recording_date,
            sequence_number=recording.sequence_number,
            data_path=recording.data_path,
            notes=recording.notes,
            values={
                "anaesthetic": recording.anaesthetic,
                "click_threshold_db": recording.click_threshold_db,
                "threshold_3khz_db": recording.threshold_3khz_db,
                "threshold_6khz_db": recording.threshold_6khz_db,
                "threshold_12khz_db": recording.threshold_12khz_db,
                "threshold_18khz_db": recording.threshold_18khz_db,
                "threshold_24khz_db": recording.threshold_24khz_db,
                "threshold_30khz_db": recording.threshold_30khz_db,
                "threshold_36khz_db": recording.threshold_36khz_db,
                "threshold_42khz_db": recording.threshold_42khz_db,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0025_dynamic_recording_schema"),
    ]

    operations = [
        migrations.RunPython(
            migrate_recordings,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
