# Generated by Codex on 2026-07-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0026_seed_and_migrate_recordings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ABRRecording",
        ),
        migrations.DeleteModel(
            name="ImagingRecording",
        ),
    ]
