# Generated by Django 4.2.30 on 2026-08-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0029_recording_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='severity',
            field=models.CharField(blank=True, choices=[('Non-recovery', 'Non-recovery'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=15),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='max_severity',
            field=models.CharField(blank=True, choices=[('Non-recovery', 'Non-recovery'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=15),
        ),
    ]
