# Generated by Django 4.2.30 on 2026-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0030_alter_mouse_severity_alter_protocol_max_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='breeding_pair',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
