# Generated by Django 4.2.30 on 2026-08-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_mouse_breeding_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Culled', 'Culled')], default='Alive', max_length=50),
        ),
    ]
