# Generated by Django 4.2.30 on 2026-08-22 11:50

from django.db import migrations, models

def create_default_protocols(apps, schema_editor):
    Protocol = apps.get_model("lab", "Protocol")

    default_protocols = [
        {
            "protocol_number": 0,
            "licence_reference": "PP123456",
            "name": "Schedule 1",
            "description": "Example non-regulated protocol",
            "allows_regulated_procedures": False,
        }]
    for protocol_data in default_protocols:
        Protocol.objects.get_or_create(**protocol_data)


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0032_alter_mouse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='allows_regulated_procedures',
            field=models.BooleanField(default=True, verbose_name='Allows regulated procedures'),
        ),
        migrations.RunPython(
            create_default_protocols,
            reverse_code=migrations.RunPython.noop,
        ),

    ]
