# Generated by Django 4.2.30 on 2026-08-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_protocol_allows_regulated_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mice', to='lab.protocol'),
        ),
    ]
