# Generated by Django 4.2.30 on 2026-08-22 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


def seed_default_species(apps, schema_editor):
    Species = apps.get_model("lab", "Species")
    Species.objects.get_or_create(
        name="Mouse",
        defaults={"active": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0037_services_project_and_genotyping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossing',
            fields=[
                ('crossing_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=500)),
                ('canonical_key', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['species__name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(
            seed_default_species,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='MouseLine',
            fields=[
                ('mouse_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_wild_type', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='lab.species')),
            ],
            options={
                'ordering': ['species__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MouseGenotype',
            fields=[
                ('mouse_genotype_id', models.AutoField(primary_key=True, serialize=False)),
                ('zygosity', models.CharField(choices=[('unknown', 'Unknown'), ('wt', 'WT'), ('het', 'Het'), ('hom', 'Hom')], default='unknown', max_length=20)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genotype_calls', to='lab.mouse')),
                ('mouse_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genotype_calls', to='lab.mouseline')),
            ],
            options={
                'ordering': ['mouse', 'mouse_line__name'],
            },
        ),
        migrations.CreateModel(
            name='CrossingLine',
            fields=[
                ('crossing_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('crossing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossing_lines', to='lab.crossing')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crossing_lines', to='lab.mouseline')),
            ],
            options={
                'ordering': ['crossing', 'line__name'],
            },
        ),
        migrations.AddField(
            model_name='crossing',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='crossings', through='lab.CrossingLine', to='lab.mouseline'),
        ),
        migrations.AddField(
            model_name='crossing',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crossings', to='lab.species'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='crossing_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mice', to='lab.crossing'),
        ),
        migrations.AddConstraint(
            model_name='mouseline',
            constraint=models.UniqueConstraint(models.F('species'), django.db.models.functions.text.Lower('name'), name='unique_mouse_line_name_per_species'),
        ),
        migrations.AddConstraint(
            model_name='mousegenotype',
            constraint=models.UniqueConstraint(fields=('mouse', 'mouse_line'), name='unique_genotype_call_per_mouse_line'),
        ),
        migrations.AddConstraint(
            model_name='crossingline',
            constraint=models.UniqueConstraint(fields=('crossing', 'line'), name='unique_line_per_crossing'),
        ),
        migrations.AddConstraint(
            model_name='crossing',
            constraint=models.UniqueConstraint(fields=('species', 'canonical_key'), name='unique_crossing_canonical_key_per_species'),
        ),
    ]
