# Generated by Django 4.2.30 on 2026-08-22 17:51

from django.db import migrations, models


def rename_double_triple_to_multiple(apps, schema_editor):
    Mouse = apps.get_model("lab", "Mouse")
    Mouse.objects.filter(crossing_type="Double_triple").update(
        crossing_type="Multiple"
    )


def rename_multiple_to_double_triple(apps, schema_editor):
    Mouse = apps.get_model("lab", "Mouse")
    Mouse.objects.filter(crossing_type="Multiple").update(
        crossing_type="Double_triple"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0038_structured_crossings"),
    ]

    operations = [
        migrations.RunPython(
            rename_double_triple_to_multiple,
            reverse_code=rename_multiple_to_double_triple,
        ),
        migrations.AlterField(
            model_name="mouse",
            name="crossing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WT", "Wild Type"),
                    ("Single", "Single Mutation"),
                    ("Multiple", "Multiple"),
                ],
                max_length=20,
            ),
        ),
    ]
